/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import java.awt.Color;

/**
 * TelaPrincipal é uma classe que representa uma janela
 * (JFrame) para selecionar a opção que deseja usar no sistema. Esta classe
 * permite selecionar a função desejada.
 * @version 1.0
 * @since 2023-06-13
 *
 * @see javax.swing.JInternalFrame
 * @see Banco.BancoMysql
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        this.getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        desktop = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        MenCadFuncionarios = new javax.swing.JMenuItem();
        MenCadBeneficios = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        MenRegistroHoras = new javax.swing.JMenuItem();
        MenGerarContraCheque = new javax.swing.JMenuItem();
        MenFolhaDePagamento = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        MenSobre = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        MenSair = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Workday");
        setBackground(new java.awt.Color(0, 204, 102));
        setResizable(false);

        desktop.setBackground(new java.awt.Color(255, 255, 255));
        desktop.setForeground(new java.awt.Color(255, 255, 255));
        desktop.setPreferredSize(new java.awt.Dimension(890, 445));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vitor Hugo\\Documents\\NetBeansProjects\\Workday\\src\\main\\resources\\workday.png")); // NOI18N

        desktop.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopLayout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jMenu3.setText("Cadastros");

        MenCadFuncionarios.setText("Funcionários");
        MenCadFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenCadFuncionariosActionPerformed(evt);
            }
        });
        jMenu3.add(MenCadFuncionarios);

        MenCadBeneficios.setText("Benefícios");
        MenCadBeneficios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenCadBeneficiosActionPerformed(evt);
            }
        });
        jMenu3.add(MenCadBeneficios);

        jMenuBar2.add(jMenu3);

        jMenu7.setText("Financeiro");

        MenRegistroHoras.setText("Registro de horas");
        MenRegistroHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenRegistroHorasActionPerformed(evt);
            }
        });
        jMenu7.add(MenRegistroHoras);

        MenGerarContraCheque.setText("Geração de contra-cheque");
        MenGerarContraCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenGerarContraChequeActionPerformed(evt);
            }
        });
        jMenu7.add(MenGerarContraCheque);

        MenFolhaDePagamento.setText("Folha de pagamento");
        MenFolhaDePagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenFolhaDePagamentoActionPerformed(evt);
            }
        });
        jMenu7.add(MenFolhaDePagamento);

        jMenuBar2.add(jMenu7);

        jMenu5.setText("Ajuda");

        MenSobre.setText("Sobre");
        MenSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenSobreActionPerformed(evt);
            }
        });
        jMenu5.add(MenSobre);

        jMenuBar2.add(jMenu5);

        jMenu6.setText("Opções");

        MenSair.setText("Sair");
        MenSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenSairActionPerformed(evt);
            }
        });
        jMenu6.add(MenSair);

        jMenuBar2.add(jMenu6);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(930, 523));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenCadBeneficiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenCadBeneficiosActionPerformed
        // TODO add your handling code here:
        TelaCadastroBeneficio beneficio = new TelaCadastroBeneficio();
        desktop.add(beneficio);
        beneficio.setVisible(true);
    }//GEN-LAST:event_MenCadBeneficiosActionPerformed

    private void MenCadFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenCadFuncionariosActionPerformed
        // TODO add your handling code here:
        TelaCadastroFuncionario funcionario = new TelaCadastroFuncionario();
        desktop.add(funcionario);
        funcionario.setVisible(true);
    }//GEN-LAST:event_MenCadFuncionariosActionPerformed

    private void MenSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenSairActionPerformed
        // TODO add your handling code here:
        if(javax.swing.JOptionPane.showConfirmDialog(null,"Deseja sair do sistema?","ATENÇÃO ",javax.swing.JOptionPane.YES_NO_OPTION )==0){
            this.dispose();
        }
    }//GEN-LAST:event_MenSairActionPerformed

    private void MenSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenSobreActionPerformed
        // TODO add your handling code here:
        TelaSobre sobre = new TelaSobre();
        desktop.add(sobre);
        sobre.setVisible(true);
    }//GEN-LAST:event_MenSobreActionPerformed

    private void MenRegistroHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenRegistroHorasActionPerformed
        // TODO add your handling code here:
        TelaRegistroHora registroHora = new TelaRegistroHora();
        desktop.add(registroHora);
        registroHora.setVisible(true);
    }//GEN-LAST:event_MenRegistroHorasActionPerformed

    private void MenGerarContraChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenGerarContraChequeActionPerformed
        // TODO add your handling code here:
        TelaGerarContracheque selecionar = new TelaGerarContracheque();
        selecionar.setVisible(true);
    }//GEN-LAST:event_MenGerarContraChequeActionPerformed

    private void MenFolhaDePagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenFolhaDePagamentoActionPerformed
        // TODO add your handling code here:
        TelaFolhaDePagamento folha = new TelaFolhaDePagamento();
        desktop.add(folha);
        folha.setVisible(true);
    }//GEN-LAST:event_MenFolhaDePagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenCadBeneficios;
    private javax.swing.JMenuItem MenCadFuncionarios;
    private javax.swing.JMenuItem MenFolhaDePagamento;
    private javax.swing.JMenuItem MenGerarContraCheque;
    private javax.swing.JMenuItem MenRegistroHoras;
    private javax.swing.JMenuItem MenSair;
    private javax.swing.JMenuItem MenSobre;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    // End of variables declaration//GEN-END:variables
}
