/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Telas;

import Banco.BancoMysql;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 * TelaCadastroBeneficio é uma classe que representa uma janela interna
 * (JInternalFrame) para o cadastro e gerenciamento de benefícios. Esta classe
 * permite adicionar, editar e excluir benefícios em um banco de dados MySQL.
 * <p>
 * A tela inclui campos para o nome do benefício e data de validade, além de uma
 * tabela para exibir os benefícios cadastrados.
 * </p>
 *
 * @version 1.0
 * @since 2023-06-13
 *
 * @see javax.swing.JInternalFrame
 * @see Banco.BancoMysql
 */
public class TelaCadastroBeneficio extends javax.swing.JInternalFrame {

    private final Set<Integer> editedRows = new HashSet<>();

    /**
     *
     * @param args
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
    }

    /**
     * Creates new form TelaCadastroUsuario
     */
    public TelaCadastroBeneficio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeBeneficio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDataValidade = new javax.swing.JFormattedTextField();
        btnAdicionarBeneficio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaBeneficio = new javax.swing.JTable();
        btnEditarBeneficio = new javax.swing.JButton();
        btnDeletarBeneficio = new javax.swing.JButton();

        setTitle("Benefícios");
        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setPreferredSize(new java.awt.Dimension(891, 445));
        setRequestFocusEnabled(false);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Novo Benefício", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        jPanel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nome do Benefício:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Data de validade:");

        try {
            txtDataValidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnAdicionarBeneficio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAdicionarBeneficio.setText("Adicionar");
        btnAdicionarBeneficio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdicionarBeneficioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDataValidade, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnAdicionarBeneficio)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDataValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionarBeneficio))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        tabelaBeneficio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tabelaBeneficio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDBeneficio", "Nome do Benefício", "Data de validade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaBeneficio.setPreferredSize(new java.awt.Dimension(321, 130));
        jScrollPane1.setViewportView(tabelaBeneficio);
        if (tabelaBeneficio.getColumnModel().getColumnCount() > 0) {
            tabelaBeneficio.getColumnModel().getColumn(0).setMinWidth(0);
            tabelaBeneficio.getColumnModel().getColumn(0).setPreferredWidth(0);
            tabelaBeneficio.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        btnEditarBeneficio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditarBeneficio.setText("Salvar alterações");
        btnEditarBeneficio.setEnabled(false);
        btnEditarBeneficio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarBeneficioMouseClicked(evt);
            }
        });

        btnDeletarBeneficio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDeletarBeneficio.setText("Excluir");
        btnDeletarBeneficio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeletarBeneficioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(btnEditarBeneficio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeletarBeneficio)
                .addContainerGap(337, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarBeneficio)
                    .addComponent(btnDeletarBeneficio))
                .addGap(18, 18, 18))
        );

        setBounds(0, 0, 891, 445);
    }// </editor-fold>//GEN-END:initComponents
/**
     * Método de evento para o botão Adicionar Benefício. Este método é chamado
     * quando o botão é clicado e adiciona um novo benefício ao banco de dados.
     *
     * @param evt evento de clique do mouse
     */
    private void btnAdicionarBeneficioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdicionarBeneficioMouseClicked
        String nome = txtNomeBeneficio.getText();
        String dataValidade = txtDataValidade.getText();

        if (!nome.isEmpty() && !dataValidade.isEmpty()) {
            try {
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                java.util.Date parsedDate = dateFormat.parse(dataValidade);
                Date sqlDate = new Date(parsedDate.getTime());

                String sql = "INSERT INTO beneficios (NomeBeneficio, DataValidade) VALUES ('" + nome + "', '" + sqlDate + "')";

                var inseriu = BancoMysql.Inserir(sql);

                if (inseriu) {
                    JOptionPane.showMessageDialog(this, "Benefício adicionado com sucesso!");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao adicionar benefício.", "Erro", JOptionPane.ERROR_MESSAGE);
            } catch (ParseException ex) {
                Logger.getLogger(TelaCadastroBeneficio.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        try {
            PreencheTabelaBenefico();
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastroBeneficio.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtNomeBeneficio.setText("");
        txtDataValidade.setText("");
    }//GEN-LAST:event_btnAdicionarBeneficioMouseClicked
    /**
     * Método para carregar os dados da tabela de benefícios. Este método
     * recupera os dados do banco de dados e preenche a tabela com esses dados.
     * @throws java.sql.SQLException
     */
    public void PreencheTabelaBenefico() throws SQLException {
        var retorno = BancoMysql.ExecutarConsulta("select * from beneficios");
        DefaultTableModel model = (DefaultTableModel) tabelaBeneficio.getModel();
        model.setNumRows(0);

        while (retorno.next()) {
            model.addRow(new Object[]{
                retorno.getInt("idBeneficios"),
                retorno.getString("NomeBeneficio"),
                retorno.getString("DataValidade")
            });
        }
        BancoMysql.FecharConexao();
        model.addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                if (e.getType() == TableModelEvent.UPDATE) {
                    int row = e.getFirstRow();
                    int column = e.getColumn();
                    editedRows.add(row);
                    btnEditarBeneficio.setEnabled(true);

                }
            }
        });
    }

    /**
     * Método de evento para o botão Editar Benefício. Este método é chamado
     * quando o botão é clicado e edita os benefícios selecionados na tabela.
     *
     * @param evt evento de clique do mouse
     */
    private void btnEditarBeneficioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarBeneficioMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabelaBeneficio.getModel();
        int qtd = 0;
        for (int row : editedRows) {
            int id = (int) model.getValueAt(row, 0);
            String nome = (String) model.getValueAt(row, 1);
            String dataValidadeStr = model.getValueAt(row, 2).toString();

            try {
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                java.util.Date parsedDate = dateFormat.parse(dataValidadeStr);
                Date dataValidade = new Date(parsedDate.getTime());

                String sql = "UPDATE beneficios SET NomeBeneficio = '" + nome + "', DataValidade = '" + dataValidade + "' WHERE idBeneficios = " + id + "";
                var atualizou = BancoMysql.Atualizar(sql);
                if (atualizou) {
                    qtd++;
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Erro ao atualizar benefício.", "Erro", JOptionPane.ERROR_MESSAGE);
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "Formato de data inválido para o benefício ID: " + id, "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }

        editedRows.clear();
        JOptionPane.showMessageDialog(this, qtd + " benefício(s) atualizado(s) com sucesso!");
        btnEditarBeneficio.setEnabled(false);
    }//GEN-LAST:event_btnEditarBeneficioMouseClicked
    /**
     * Método de evento para o botão Deletar Benefício. Este método é chamado
     * quando o botão é clicado e deleta os benefícios selecionados na tabela.
     *
     * @param evt evento de clique do mouse
     */
    private void btnDeletarBeneficioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeletarBeneficioMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabelaBeneficio.getModel();
        int selectedRow = tabelaBeneficio.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione um benefício para deletar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int id = (int) tabelaBeneficio.getValueAt(selectedRow, 0);

        int confirm = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja deletar este benefício?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                String sql = "DELETE FROM beneficios WHERE idBeneficios = " + id;
                var deletou = BancoMysql.Deletar(sql);

                if (deletou) {
                    model.removeRow(selectedRow);
                    JOptionPane.showMessageDialog(this, "Benefício deletado com sucesso!");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao deletar benefício.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeletarBeneficioMouseClicked
    /**
     * Método de evento para a abertura do formulário. Este método é chamado
     * quando a janela interna é aberta e carrega os dados da tabela.
     *
     * @param evt evento de abertura da janela interna
     */
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        try {
            PreencheTabelaBenefico();
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastroBeneficio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarBeneficio;
    private javax.swing.JButton btnDeletarBeneficio;
    private javax.swing.JButton btnEditarBeneficio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaBeneficio;
    private javax.swing.JFormattedTextField txtDataValidade;
    private javax.swing.JTextField txtNomeBeneficio;
    // End of variables declaration//GEN-END:variables
}
